### ISSUE TITLE
Question: What is the reason Grapoi returns Symbol.iterator in Path.quads()?

### ISSUE THREAD

**Issue by danielbeeke** [rdf-ext/grapoi#4]
It might be interesting to be able to use native Array methods directly on the results of .quads()

Before:
```TypeScript
const datatypes = [...pointer.in([sh('datatype')]).quads()].map((quad: Quad) => quad.object.value)
```

After:
```TypeScript
const datatypes = pointer.in([sh('datatype')]).quads().map((quad: Quad) => quad.object.value)
```

**Comment by danielbeeke** [comment]
```TypeScript
const datatypes = shaclPointer.out([sh('datatype')]).values
```

**Comment by bergos** [comment]
The `.quads()` method doesn't return unique quads. It would require dependency on a factory that implements `DatasetCore,` and I wanted to avoid that. I thought most people would call `rdf.dataset(ptr.quads())` for further processing. Wrapping the result into an Array would give the order more meaning. That opens the discussion about BFS vs. DFS. Maybe an argument should be added to control the order. I'm open to changing the return type once more use cases are collected, but at the moment I don't have enough experience to judge whether it's a good or bad idea and how it should be implemented.

**Comment by danielbeeke** [comment]
Thanks, and it is not an issue for me anymore I think when I can use .values
