### ISSUE TITLE
It would be nice to have some kind of API that would work with language tags.

### ISSUE THREAD

**Issue by danielbeeke** [rdf-ext/grapoi#5]
It would be nice to have some kind of API that would work with language tags.

I would like something like:

```turtle
sh:property [
  sh:name "given name"@en ;
  sh:name "Gegeven name"@nl ;
  sh:description "Wie werden Sie genannt?"@de ;
]
```

```TypeScript

shaclPointer.setLanguagePriorities(['en', 'nl', '', '*'])

const name = shaclPointer.out([sh('name')]).value
// given name
const description = shaclPointer.out([sh('description')]).value
// Wie werden Sie genannt?

```

If the term is a langString or string it would return the first match from the given language priorities.

- The '' would match strings without a language tag.
- '*' would match any other language.

Would you be open to a PR for something like that?

**Comment by danielbeeke** [comment]
Something like this:
[grapoi+1.0.0.patch.txt](https://github.com/rdf-ext/grapoi/files/11177433/grapoi%2B1.0.0.patch.txt)

**Comment by bergos** [comment]
You can use the `.best()` or `.score()` methods combined with the [language](https://github.com/rdfjs-base/score/#languagelanguages) function of the `@rdfjs/score` package:

```javascript
shaclPointer.best(score.language(['en', 'nl', '', '*'])).value
```

That gives you a lot of flexibility. I'm often using the `pageRank` function to find the root of unknown RDF data. I think it requires revisiting the list of functions, especially the functions to combine other score functions, but you can rely on the `language` and `pageRank` functions as they are defined right now.

**Comment by danielbeeke** [comment]
Thanks that is very cool!
